In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [3]:
list = [1,2,3,4,"hello"]
print(list)

[1, 2, 3, 4, 'hello']


In [4]:
l = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(l)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# start(inclusive), stop(exclusive), step size
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [6]:
arr = np.zeros([5,5])
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
arr = np.ones([2,6])
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [8]:
# start,stop,total number to print with equidistance
np.linspace(1,2,2)

array([1., 2.])

In [9]:
#normalisation between 0 and 1
a = np.random.random()
print(a)
np.random.rand(3)

0.3419619117669821


array([0.5851374 , 0.18847991, 0.09102464])

In [10]:
#standardization between -3 and 3
np.random.randn(5)

array([ 0.14794284, -1.48006772, -0.23764399,  0.47296415,  0.39331478])

In [11]:
#to generate 5 random integers in aarray
np.random.randint(1,20,5)

array([ 5, 19,  9, 14,  1])

In [12]:
arr = np.array([[3,1],[34,44],[11,31]])
print(arr)

[[ 3  1]
 [34 44]
 [11 31]]


In [13]:
#attributes(no need of paranthesis)
print(arr.shape)
print(arr.size)
print(arr.dtype)

(3, 2)
6
int64


In [14]:
# array methods
print(arr.min())
print(arr.argmin()) # index of min
print(arr.max())
print(arr.argmax()) # index of max
print(arr.sum())
print(np.sum(arr))

1
1
44
3
124
124


In [15]:
np.sum(arr,axis=1) # Rows

array([ 4, 78, 42])

In [16]:
np.sum(arr,axis=0) # Columns

array([48, 76])

In [17]:
print(arr.mean())

20.666666666666668


In [18]:
print(arr.std())

16.438437341250605


In [19]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [20]:
arr = arr.reshape(5,6) # 5x6 matrix since 30 elemtns there
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [21]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
#array slicing
print(arr[:4]) # start from 0 index
print(arr[:])
print(arr[2:]) # stop till size of arr

[10 11 12 13]
[10 11 12 13 14 15 16 17 18 19 20]
[12 13 14 15 16 17 18 19 20]


In [23]:
arr = np.arange(1,21).reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [24]:
print(arr[4,0])
arr_reshape = arr[:2,0:]
print(arr_reshape)
arr_reshape.shape

17
[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [25]:
#bool indexing slicing
bool_index = arr%2 ==0
bool_index

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [26]:
arr[bool_index] # returns 1d array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
a1 = np.arange(1,11)
a2 = np.arange(11,21)
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1**a2)
print(a2/a1)
print(a2//a1)

[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[                  1                4096             1594323
           268435456         30517578125       2821109907456
     232630513987207   18014398509481984 1350851717672992089
 7766279631452241920]
[11.          6.          4.33333333  3.5         3.          2.66666667
  2.42857143  2.25        2.11111111  2.        ]
[11  6  4  3  3  2  2  2  2  2]


In [28]:
#broadcasting
arr = np.arange(1,21)
print(arr +10)
print(arr-10)
print(arr*10)
print(arr**2)
print(arr/10)
print(arr//10)
# these operations can be performed for 2d array as well

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9 2. ]
[0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2]


In [29]:
#deep copy and shallow copy 
"""
1)shallow copy means slicing and deep copy means copy() 
2) b = a
   → Assignment (no copy) i.e., they are same array object point to same data
3) b = a[:] or b = a[1:] etc..
   → Shallow copy / View
   → two different array objects a and b point to same data
4) b = a.copy()
   → Deep copy
   → two different array objects a and b point to two diffrent array copies 
5) b+=10 does not create new array bt b = b+10 creates new array b
"""
a = np.arange(1,11)
print(a)
b = a
print(b)
b +=10
#b=b+10
#b[2]=22
print(b)
print(a)
print("================================")
a = np.arange(1,11)
c = a[1:8]
print(c)
print(a)
c[3] = 333
print(c)
print(a)
print("================================")
a = np.arange(1,11)
d = a.copy()
print(a)
print(d)
d[3]=123
print(d)
print(a)
print("================================")

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
[  2   3   4 333   6   7   8]
[  1   2   3   4 333   6   7   8   9  10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3 123   5   6   7   8   9  10]
[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
#Matrix operations
A = np.arange(1,7).reshape(3,2)
B = np.arange(6,12).reshape(2,3)
print(A)
print(B)
print(A@B)
print(np.dot(A,B))
print(A.T)
B.T

[[1 2]
 [3 4]
 [5 6]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 24  27  30]
 [ 54  61  68]
 [ 84  95 106]]
[[ 24  27  30]
 [ 54  61  68]
 [ 84  95 106]]
[[1 3 5]
 [2 4 6]]


array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [31]:
# Stacking array(we use vectors or 1d arrays only)
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.column_stack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [38]:
# splitting array 
arr = np.arange(1,17).reshape(4,4)
print(arr)
print(np.vsplit(arr,2))
print(np.vsplit(arr,4))
print(np.hsplit(arr,2))
print(np.hsplit(arr,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
