In [2]:
import numpy as np

In [38]:
# valid suduko
arr = np.array([[5,3,4,6,7,8,9,1,2],
               [6,7,2,1,9,5,3,4,8],
               [1,9,8,3,4,2,5,6,7],
               [8,5,9,7,6,1,4,2,3],
               [4,2,6,8,5,3,7,9,1],
               [7,1,3,9,2,4,8,5,6],
               [9,6,1,5,3,7,2,8,4],
               [2,8,7,4,1,9,6,3,5],
               [3,4,5,2,8,6,1,7,9]])
print(arr)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [39]:
print(np.sum(arr,1))#rows
print(np.sum(arr,1)==45)
print(np.sum(arr,0))#columns
print(np.sum(arr,0)==45)

[45 45 45 45 45 45 45 45 45]
[ True  True  True  True  True  True  True  True  True]
[45 45 45 45 45 45 45 45 45]
[ True  True  True  True  True  True  True  True  True]


In [40]:
for i in range(0,7,3):
    for j in range(0,7,3):
        a = arr[i:i+3,j:j+3]
        print(a)
        print(np.sum(a))

[[5 3 4]
 [6 7 2]
 [1 9 8]]
45
[[6 7 8]
 [1 9 5]
 [3 4 2]]
45
[[9 1 2]
 [3 4 8]
 [5 6 7]]
45
[[8 5 9]
 [4 2 6]
 [7 1 3]]
45
[[7 6 1]
 [8 5 3]
 [9 2 4]]
45
[[4 2 3]
 [7 9 1]
 [8 5 6]]
45
[[9 6 1]
 [2 8 7]
 [3 4 5]]
45
[[5 3 7]
 [4 1 9]
 [2 8 6]]
45
[[2 8 4]
 [6 3 5]
 [1 7 9]]
45


In [174]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [175]:
#Get the shape of the matrix
print(np.shape(data))
print(data.shape)

(5, 3)
(5, 3)


In [176]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [177]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [178]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [179]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [180]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [181]:
#Find how many students are younger than 19.
data[data[:,0]<19]

array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [182]:
#Calculate the average marks in each subject (column-wise mean).
print(np.mean(data[:,1]))
print(np.mean(data[:,2]))
print("====================")
print(np.mean(data[:,1:3],axis = 1))
print(np.mean(data[:,1:3],axis = 0))

86.6
83.2
[84.  92.5 88.  70.  90. ]
[86.6 83.2]


In [183]:
#Get data of students who scored at least 80 in both subjects.
data[ (data[:,1]>=80) & (data[:,2]>=80) ]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [186]:
# replace all science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])